### ISSUE TITLE
有预训练数据集就好了

### ISSUE THREAD

**Issue by guotong1988** [CLUEbenchmark/CLUEDatasetSearch#10]

**Comment by liangjianqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by guotong1988** [comment]
https://github.com/CLUEbenchmark/CLUEDatasetSearch/tree/master/%E8%AF%AD%E6%96%99%E5%BA%93
